name: symfony-blog
recipe: symfony
config:
  webroot: public
  php: '8.1'
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  database:
    type: mariadb
    creds:
      user: symfony-blog
      password: symfony-blog
      database: symfony-blog